### ISSUE TITLE
Wifi Direct implementation

### ISSUE THREAD

**Issue by isurunuwanthilaka** [isurunuwanthilaka/d2d-app-android#12]
Wifi direct link establishment. Following tasks needed to be carried out.

- First time authorization

- Establishing link

- Uploading the file

- Terminating link after successful transfer

**Comment by isurunuwanthilaka** [comment]
Establishing the link part is done

**Comment by isurunuwanthilaka** [comment]
Now a single message can be sent over the link

**Comment by lochana-chathura** [comment]
uni-directional file transfer over the link is done

**Comment by lochana-chathura** [comment]
bi-directional file transfer over the link is done

**Comment by lochana-chathura** [comment]
file transfer over the link tested for jpg and pdf file formats
