### ISSUE TITLE
App crash randomly

### ISSUE THREAD

**Issue by isurunuwanthilaka** [isurunuwanthilaka/d2d-app-android#39]

**Comment by lochana-chathura** [comment]
Overridden thread policy changed to default. So no crashing due to thread policy.

**Comment by lochana-chathura** [comment]
[https://stackoverflow.com/a/45425507/10218426](url)
@isurunuwanthilaka could you check if this is the reason for crashing

**Comment by isurunuwanthilaka** [comment]
@lochana-chathura  I FIXED the bug. Sync with the master, if crashes again let me know!
