### ISSUE TITLE
File screen not refreshed when new files added

### ISSUE THREAD

**Issue by isurunuwanthilaka** [isurunuwanthilaka/d2d-app-android#48]
When I add a file by downloading from the cloud that new file is not visible in the file screen even if I go to another tab and come back. When I close and reopen the app, file is shown.

**Comment by lochana-chathura** [comment]
Now file screen is refreshed when switching between fragments. Yet it is not working for adjacent tab switches.

**Comment by lochana-chathura** [comment]
> 
> 
> Now file screen is refreshed when switching between fragments. Yet it is not working for adjacent tab switches.

reason found to be https://stackoverflow.com/a/57123353/10218426

**Comment by isurunuwanthilaka** [comment]
tabs are itself a fragment ne, so interchanging between fragments means interchanging between tabs also

**Comment by lochana-chathura** [comment]
> 
> 
> tabs are itself a fragment ne, so interchanging between fragments means interchanging between tabs also

it is obvious ne. what I wanted to highlight was still problem exist for adjacent fragment switches.

**Comment by lochana-chathura** [comment]
a workaround found at https://stackoverflow.com/a/25101237/10218426. 
Implemented and tested successfully.
